/**
 * Generate the scenario JSON INPUT TEMPLATE for desk research and AI-assisted
 * data entry.
 *
 * The audience writes a scenario file by hand (or has a model write one) and
 * needs to know, without reading the code: which fields exist, which are
 * required, which id strings are legal, what units each number is in, what
 * `null` means, and what will be rejected.
 *
 * GENERATED, never hand-written — the vocabularies come from the reference
 * bundle and the field list from the same artifact §22 renders, so the
 * template cannot drift from the schema it describes. Re-run after any
 * schema change:
 *
 *   npm run corridor:template
 */
import { readFileSync, writeFileSync } from "node:fs";
import {
  parseRefBundle,
  SCHEMA_VERSION,
  toCompleteScenarioJson,
} from "@h2map/corridor-schema";
import { emptyScenario } from "../../apps/web/lib/corridor/scenarioDefaults";

const ROOT = new URL("../../", import.meta.url);
const BUNDLE_ID = "2026-08-16-vessel-v2";

const bundle = parseRefBundle(
  JSON.parse(
    readFileSync(new URL(`data/corridor-ref/${BUNDLE_ID}.json`, ROOT), "utf8"),
  ),
);

const fuelRef = JSON.parse(
  readFileSync(new URL("data/fuel-emissions-ref/2026-08-14-seed-3.json", ROOT), "utf8"),
) as { n2oSlip: { scenarios: { id: string; label: string }[] } };

/** The complete form of a blank scenario: every field, unset ones null. */
const template = toCompleteScenarioJson(emptyScenario());

const ids = {
  vessels: bundle.vesselTypes.map((v) => v.id),
  fuels: bundle.fuels.map((f) => f.id),
  countries: bundle.countries.map((c) => c.id),
  n2o: fuelRef.n2oSlip.scenarios.map((s) => s.id),
};

const lines: string[] = [
  "<!-- GENERATED by scripts/corridor/gen-input-template.ts — do not edit by hand. -->",
  "",
  "# Corridor scenario — JSON input template",
  "",
  `Schema version **${SCHEMA_VERSION}** · reference bundle \`${BUNDLE_ID}\``,
  "",
  "This is the contract for writing a scenario file by hand, for desk",
  "research or AI-assisted data entry. A file that follows it loads without",
  "edits.",
  "",
  "Two failure modes, and they are not symmetric. A **wrong value** — bad",
  "type, unknown id, out of bounds — is rejected on import, naming the",
  "offending path. A **wrong key** is not: unknown keys are ignored in",
  "silence, so a misspelled field imports cleanly and is simply dropped.",
  "Rule 5 is about that, and it is the one to be careful of.",
  "",
  "## The five rules",
  "",
  "1. **Keep every key; write `null`, never omit.** Behaviour verified",
  "   against the importer: a missing *scalar* is rejected outright (even a",
  "   nullable override — `null` and absent are NOT the same to the",
  "   validator), while a missing optional *block* such as `financing` is",
  "   accepted and read as \"module off\". Do not rely on that distinction:",
  "   copy the whole template.",
  "2. **`null` means \"use the model's own value\"** — the benchmark, the",
  "   derived figure, or \"module off\". It does NOT mean zero. Writing `0`",
  "   where you meant \"leave it alone\" charges a real zero and changes the",
  "   result.",
  "3. **Only fill a field you have a source for.** Every non-null number is",
  "   an OVERRIDE: it replaces a benchmark the model would otherwise derive,",
  "   and the UI marks it so a reader can see what you asserted.",
  "4. **Id strings must come from the lists below.** An unrecognised",
  "   `fuelId`, `typeId` or `countryId` is a hard error — the model never",
  "   falls back to a default for an id it does not know.",
  "5. **An unknown key is SILENTLY IGNORED — this is the dangerous one.**",
  "   Misspell a field (`oneWayDistanceNM`, `capexUsdM`) and the file still",
  "   imports; your value is dropped and the model quietly uses its own.",
  "   Nothing warns you. Check every number you meant to set actually shows",
  "   an OVERRIDE badge in the UI before trusting the result.",
  "",
  "## What you must NOT do",
  "",
  "| Don't | Why |",
  "|---|---|",
  "| Set `schemaVersion` to anything else | It pins the shape. A LOWER number is migrated on load (your file is reinterpreted); a higher one is rejected. |",
  "| Change `refBundleId` | It pins the reference data (vessel table, fuels, countries). Bundles are immutable; an unknown id is an error. |",
  "| Use `0` to mean \"no override\" | `0` is a real value. Use `null`. |",
  "| Fill both a price override and production CAPEX/OPEX on a `purchase` side | Purchase forces production lines to zero — the CAPEX you wrote is discarded, which looks like a bug. |",
  "| Override one side's `fuelTonnesPerVesselYear` alone | The two sides then carry different delivered energy, and CO₂ abated compares unequal transport work. The model raises an amber note; fix the pairing or state why. |",
  "| Hand-write `buildHere` | It is written by the map when you evaluate a site. Leave the whole block null unless you are round-tripping a file that already had one. |",
  "| Put a fleet total in `capexUsdMPerShip` | It is PER SHIP; the model multiplies by `cargo.vessels`. A fleet number here is silently ×N too large. |",
  "",
  "## Allowed id values",
  "",
  "| Field | Allowed values |",
  "|---|---|",
  `| \`vessel.typeId\` | ${ids.vessels.map((v) => `\`${v}\``).join(", ")} |`,
  `| \`green.fuelId\`, \`fossil.fuelId\` | ${ids.fuels.map((f) => `\`${f}\``).join(", ")} |`,
  `| \`cargo.countryId\`, \`cargo.countryBId\` | ${ids.countries.map((c) => `\`${c}\``).join(", ")} |`,
  `| \`*.emissions.n2oScenarioId\` | ${ids.n2o.map((n) => `\`${n}\``).join(", ")} (e-ammonia only) |`,
  "| `*.sourcing` | `purchase`, `build-plant`, `build-here` |",
  "| `cargo.routeType` | `point-to-point`, `single-point` |",
  "| `cargo.unit` | `tonne`, `teu` |",
  "| `flags.emissionsBasis` | `combustion`, `wellToWake` (the app default) |",
  "| `flags.rateBasis` | `nominal`, `real` |",
  "| `regulation.emissions.framework` | `fueleu`, `imo` |",
  "| `financing.structure` | `amortizing`, `bullet` |",
  "| `cargo.routedDistance.via` | `panama`, `suez`, or `null` |",
  "",
  "## Units and bounds",
  "",
  "Getting a unit wrong is the most common way a researched scenario comes",
  "out wrong while still importing cleanly. The model cannot detect it.",
  "",
  "| Field | Unit | Bounds |",
  "|---|---|---|",
  "| `cargo.oneWayDistanceNm` | nautical miles, **one way** | > 0 |",
  "| `cargo.roundtripsPerYear` | roundtrips per vessel per year | > 0 |",
  "| `cargo.vessels` | ships | integer > 0 |",
  "| `cargo.unitsPerYear` | cargo units per year (`unit` says which) | ≥ 0 |",
  "| `cargo.startYear` | calendar year | 2000–2100 |",
  "| `cargo.horizonYears` | years modelled | 1–40 |",
  "| `cargo.inflation`, `cargo.waccOverride` | **fraction**, not percent (0.02 = 2%) | finite |",
  "| `vessel.*.capexUsdMPerShip` | USD million, **per ship** | ≥ 0 |",
  "| `vessel.*.opexUsdMPerShipPerYear` | USD million per year, **per ship** | ≥ 0 |",
  "| `*.overrides.priceUsdPerTonne` | USD per tonne of fuel | ≥ 0 |",
  "| `*.overrides.fuelTonnesPerVesselYear` | tonnes per **vessel** per year | ≥ 0 |",
  "| `*.overrides.lhvMjPerTonne` | MJ per tonne | > 0 |",
  "| `*.overrides.combustionEfTco2PerTonne` | tCO₂ per tonne of fuel | ≥ 0 |",
  "| `*.overrides.wtwGco2PerMj` | gCO₂e per MJ | ≥ 0 |",
  "| `*.overrides.prod*/portStorage*/barge*UsdM` | USD million (CAPEX) or USD million/year (OPEX) | ≥ 0 |",
  "| `*.emissions.pilotShare` | fraction of energy | 0–1 |",
  "| `*.emissions.certifiedWttGco2ePerMj` | gCO₂e per MJ, well-to-**tank** | > 0 |",
  "| `regulation.eurUsd` | USD per EUR | > 0 |",
  "| `regulation.ets.euaEurPerTonne` | EUR per tonne CO₂ | ≥ 0 |",
  "| `regulation.*.scope` | fraction of the voyage in scope | 0–1 |",
  "| `financing.*Rate`, `debtShare`, `*Support` | fraction | 0–1 |",
  "",
  "## What the model derives — do not research these",
  "",
  "Leave these `null`. The model computes them, and an override replaces a",
  "figure that is consistent with the rest of the scenario with one that may",
  "not be.",
  "",
  "- **Fuel consumption** (`*.overrides.fuelTonnesPerVesselYear`) —",
  "  `2 × oneWayDistanceNm × roundtripsPerYear × GJ/nm × 1000 ÷ LHV`. Set it",
  "  only to reproduce a published burn, and set **both sides** if you set",
  "  either, or the energy-parity check will flag the mismatch.",
  "- **Vessel CAPEX/OPEX** — the benchmark is the vessel type's figure, and",
  "  for the green side × (1 + the fuel's readiness premium).",
  "- **Emission factors** (`combustionEfTco2PerTonne`, `lhvMjPerTonne`,",
  "  `wtwGco2PerMj`) — derived from the fuel-emissions dataset. Override only",
  "  with a certified pathway value you can cite.",
  "- **Fossil port/vessel CAPEX** — 0 by rule (existing infrastructure).",
  "  Override only when the comparison genuinely builds new fossil assets.",
  "",
  "## Minimum viable scenario",
  "",
  "The smallest set of decisions that produces a meaningful result. Everything",
  "else can stay on its benchmark:",
  "",
  "1. `cargo`: `countryId`, `oneWayDistanceNm`, `startYear`, `horizonYears`,",
  "   `unitsPerYear`, `vessels`, `roundtripsPerYear`",
  "2. `vessel.typeId`",
  "3. `green.fuelId` + `green.sourcing`, `fossil.fuelId` + `fossil.sourcing`",
  "4. `regulation`: switch on the schemes that apply (`enabled: true`)",
  "",
  "With those set and everything else `null`, the model derives consumption",
  "from the geometry, prices fuel from the bundle, and costs vessels from the",
  "type — a complete, internally consistent scenario.",
  "",
  "## The template",
  "",
  "Copy this whole object. Replace values; keep every key.",
  "",
  "```json",
  JSON.stringify(template, null, 2),
  "```",
  "",
  "## Checking your file before you rely on it",
  "",
  "1. Import it. A rejected file names the offending path — fix that path,",
  "   do not delete the field.",
  "2. Look for **OVERRIDE badges**. Every one is something you asserted. If",
  "   you did not mean to assert it, set it back to `null`.",
  "3. Check the **energy-parity note** on the Results Energy card. If it is",
  "   showing, your two fuel burns describe different amounts of transport",
  "   work and the CO₂-abated figure is comparing unlike with unlike.",
  "4. Sanity-check the derived fuel burn against the vessel: a Handymax on a",
  "   9,500 nm corridor at 3 roundtrips burns ~4,500 t of LSFO a year. If",
  "   your figure is far off, the distance or roundtrip count is likely wrong.",
  "",
];

const OUT = new URL("docs/corridor/input-template.md", ROOT);
writeFileSync(OUT, lines.join("\n"), "utf8");
console.log(
  `wrote docs/corridor/input-template.md (schema v${SCHEMA_VERSION}, bundle ${BUNDLE_ID})`,
);
