/**
 * Generates apps/web/components/corridor/routeMapLand.ts — the simplified
 * world coastline rings (lon/lat, NOT projected) the corridor route map
 * draws. Source: data/geo/ne_110m_countries.geojson (Natural Earth 110m,
 * public domain). Douglas-Peucker simplified and small islands dropped so
 * the bundled module stays ~100 KB.
 *
 * Run: npx tsx scripts/geo/gen-route-map-land.ts
 * (The decoupling chart's coastline module was generated by an
 * uncommitted script — this one is committed so the file is reproducible.)
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

type Ring = [number, number][];

const SRC = path.join(process.cwd(), "data/geo/ne_110m_countries.geojson");
const OUT = path.join(process.cwd(), "apps/web/components/corridor/routeMapLand.ts");

const TOLERANCE_DEG = 0.35;
const MIN_RING_AREA_DEG2 = 0.8; // drops islets that vanish at map scale

function rdp(pts: Ring, tol: number): Ring {
  if (pts.length < 3) return pts;
  const [ax, ay] = pts[0]!;
  const [bx, by] = pts[pts.length - 1]!;
  const dx = bx - ax;
  const dy = by - ay;
  const len = Math.hypot(dx, dy) || 1e-12;
  let imax = 0;
  let dmax = -1;
  for (let i = 1; i < pts.length - 1; i += 1) {
    const [px, py] = pts[i]!;
    const d = Math.abs(dx * (ay - py) - dy * (ax - px)) / len;
    if (d > dmax) {
      dmax = d;
      imax = i;
    }
  }
  if (dmax > tol) {
    const left = rdp(pts.slice(0, imax + 1), tol);
    const right = rdp(pts.slice(imax), tol);
    return [...left.slice(0, -1), ...right];
  }
  return [pts[0]!, pts[pts.length - 1]!];
}

function ringArea(ring: Ring): number {
  let s = 0;
  for (let i = 0; i < ring.length; i += 1) {
    const [x1, y1] = ring[i]!;
    const [x2, y2] = ring[(i + 1) % ring.length]!;
    s += x1 * y2 - x2 * y1;
  }
  return Math.abs(s) / 2;
}

/** Simplify a closed ring: split at the farthest point from the start so
 *  RDP's baseline is never degenerate (first == last collapses it). */
function simplifyRing(ring: Ring): Ring {
  const open = ring[0]![0] === ring[ring.length - 1]![0] &&
    ring[0]![1] === ring[ring.length - 1]![1]
    ? ring.slice(0, -1)
    : ring;
  if (open.length < 4) return open;
  let k = 1;
  let best = -1;
  for (let i = 1; i < open.length; i += 1) {
    const d =
      (open[i]![0] - open[0]![0]) ** 2 + (open[i]![1] - open[0]![1]) ** 2;
    if (d > best) {
      best = d;
      k = i;
    }
  }
  const a = rdp(open.slice(0, k + 1), TOLERANCE_DEG);
  const b = rdp([...open.slice(k), open[0]!], TOLERANCE_DEG);
  return [...a.slice(0, -1), ...b.slice(0, -1)];
}

const gj = JSON.parse(readFileSync(SRC, "utf8")) as {
  features: { geometry: { type: string; coordinates: unknown } }[];
};

const rings: Ring[] = [];
for (const f of gj.features) {
  const g = f.geometry;
  const polys =
    g.type === "Polygon"
      ? [g.coordinates as Ring[]]
      : g.type === "MultiPolygon"
        ? (g.coordinates as Ring[][])
        : [];
  for (const poly of polys) {
    const outer = poly[0];
    if (!outer || ringArea(outer) < MIN_RING_AREA_DEG2) continue;
    const simplified = simplifyRing(outer);
    if (simplified.length >= 3 && ringArea(simplified) >= MIN_RING_AREA_DEG2) {
      rings.push(simplified.map(([lon, lat]) => [
        Math.round(lon * 100) / 100,
        Math.round(lat * 100) / 100,
      ]));
    }
  }
}

rings.sort((a, b) => ringArea(b) - ringArea(a));

const lines: string[] = [];
lines.push("/**");
lines.push(" * World coastline rings for the corridor route map, in LON/LAT");
lines.push(" * (unprojected — the map projects at render time, so any corridor");
lines.push(" * window works). Generated from data/geo/ne_110m_countries.geojson");
lines.push(" * (Natural Earth 110m, public domain) by");
lines.push(" * scripts/geo/gen-route-map-land.ts — do not hand-edit; re-run the");
lines.push(" * script instead.");
lines.push(" */");
lines.push("");
lines.push("export type LonLat = readonly [number, number];");
lines.push("");
lines.push("export const LAND: readonly (readonly LonLat[])[] = [");
for (const ring of rings) {
  const body = ring.map(([lon, lat]) => `[${lon}, ${lat}]`).join(", ");
  const row = `  [${body}],`;
  if (row.length <= 100) {
    lines.push(row);
  } else {
    lines.push("  [");
    let cur = "   ";
    for (const [lon, lat] of ring) {
      const tok = ` [${lon}, ${lat}],`;
      if (cur.length + tok.length > 98) {
        lines.push(cur);
        cur = "   ";
      }
      cur += tok;
    }
    lines.push(cur);
    lines.push("  ],");
  }
}
lines.push("];");
lines.push("");

writeFileSync(OUT, lines.join("\n"), "utf8");
const kb = Buffer.byteLength(lines.join("\n"), "utf8") / 1024;
console.log(`wrote ${OUT}: ${rings.length} rings, ${kb.toFixed(0)} KB`);
